### ISSUE TITLE
com.rxjava.rxlife.OutsideScopeException: View is not attached

### ISSUE THREAD

**Issue by mycrossroads** [liujingxing/RxLife#17]
自定义view，经常性的报这个错误，有什么好的方式避免么？
com.rxjava.rxlife.OutsideScopeException: View is not attached!
        at com.rxjava.rxlife.ViewScope.onScopeStart(ViewScope.java:45)
        at com.rxjava.rxlife.AbstractLifecycle.addObserverOnMain(AbstractLifecycle.java:58)
        at com.rxjava.rxlife.AbstractLifecycle.addObserver(AbstractLifecycle.java:34)
        at com.rxjava.rxlife.LifeObserver.onSubscribe(LifeObserver.java:29)
        at io.reactivex.internal.operators.observable.ObservableDetach$DetachObserver.onSubscribe(ObservableDetach.java:66)

**Comment by liujingxing** [comment]
这是因为你的view还没添加到窗口上就发请求了，RxLife.asXxx/toXxx方法第二个参数传入true可以避免这个问题
