### ISSUE TITLE
使用.to操作符后 ，crash

### ISSUE THREAD

**Issue by yulinzhuang** [liujingxing/RxLife#23]
hi 
使用.to操作符后 ，crash

2021-12-16 15:16:50.071 18042-18042/com.tpv.rain.rxjava3test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tpv.rain.rxjava3test, PID: 18042
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
        at com.rxjava.rxlife.ObjectHelper.requireNonNull(ObjectHelper.kt)
        at com.rxjava.rxlife.ObservableLife.subscribe(ObservableLife.java:64)
        at com.tpv.rain.rxjava3test.SecondActivity.testLeak(SecondActivity.java:36)
        at com.tpv.rain.rxjava3test.SecondActivity.onResume(SecondActivity.java:29)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
        at android.app.Activity.performResume(Activity.java:6766)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3377)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3440)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2713)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.tpv.rain.rxjava3test-2/base.apk"],nativeLibraryDirectories=[/data/app/com.tpv.rain.rxjava3test-2/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.rxjava.rxlife.ObjectHelper.requireNonNull(ObjectHelper.kt) 
        at com.rxjava.rxlife.ObservableLife.subscribe(ObservableLife.java:64) 
        at com.tpv.rain.rxjava3test.SecondActivity.testLeak(SecondActivity.java:36) 
        at com.tpv.rain.rxjava3test.SecondActivity.onResume(SecondActivity.java:29) 
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269) 
        at android.app.Activity.performResume(Activity.java:6766) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3377) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3440) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2713) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 

---------------------------------------------------------------------
配置：
    //RxJava的依赖包
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
    //RxAndroid的依赖包
    implementation 'io.reactivex.rxjava3:rxjava:3.0.0'

   implementation 'com.github.liujingxing.rxlife:rxlife-rxjava3:2.2.1'

code（java）:
@Override
    protected void onResume() {
        super.onResume();
        testLeak();
    }

    private void testLeak(){
        Observable.timer(1, TimeUnit.SECONDS)
                 .to(RxLife.to(this))
                .subscribe(new Observer<Long>() {
                    @Override
                    public void onSubscribe(@NonNull Disposable d) {

                    }

                    @Override
                    public void onNext(@NonNull Long aLong) {
                        LogUtil.d(TAG, "[testLeak] onNext:"+aLong);
                    }

                    @Override
                    public void onError(@NonNull Throwable e) {
                        LogUtil.d(TAG, "[testLeak] onError");
                    }

                    @Override
                    public void onComplete() {
                        LogUtil.d(TAG, "[testLeak] onComplete");
                    }
                });

    }

**Comment by liujingxing** [comment]
应该是你kotlin版本不对，升级下试试

**Comment by yulinzhuang** [comment]
配置kotlin kotlin_version = '1.5.31'，正常
